"""
Django settings for mydjango project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wsta^y4h-jfb)z&$#irks2k&81!=o9-lv&id*rc$qgx^$rm1#x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'monitor', # 添加监控app到配置中
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mydjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mydjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# 默认使用的sqlite

default = {
    # 'ENGINE': 'django.db.backends.sqlite3',
    # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    'ENGINE': 'django.db.backends.mysql',
    'NAME': 'test',
    'USER': 'root',
    'PASSWORD': 'root',
    'HOST': '127.0.0.1',
}
dev = {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': 'tj_product_data_bi',
    'USER': 'bi_rd_data_w',
    'PASSWORD': 'ttGo7XmAZ6kJYyrjVbZh',
    'HOST': '10.2.98.73',
}
tjlocal = {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': 'djiango',
    'USER': 'root',
    'PASSWORD': 'wsjia369X',
    'HOST': 'localhost',
}


DATABASES = {
    'default': default
}
# 为所有的model生成数据迁移
# python manage.py makemigrations app名可选
# 生成0001_initial.py文件
# python manage.py migrate 检测正确性,并生成数据表, 会自动创建id
# python manage.py sqlmigrate monitor 0001 查看创建语句
# ---------- 常见的数据类型
# models.ForeignKey
# models.DateField
# models.IntegerField
# models.IPAddressField
# models.FileField
# models.ImageField


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

# 需要的依赖包
# 创建并打开list_req.txt文件
#
# vim list_req.txt
#
# 复制下面的包名到list_req.txt
#
# Django==1.11
# olefile==0.44
# Pillow==4.2.1
# PyMySQL==0.7.11
# pytz==2017.2
