# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-06-30 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('user', models.CharField(max_length=32)),
                ('active', models.CharField(default=0, max_length=2)),
            ],
        ),
    ]
