# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-06-30 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='active',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
