# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-07-02 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20190630_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=32)),
                ('taskCount', models.IntegerField(default=0, max_length=10)),
                ('lastGeneTime', models.CharField(max_length=32)),
                ('wc_l', models.IntegerField(default=0, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='crontab',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='generateFile',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
